language: node_js
node_js:
- 16
branches: 
  only: 
    - main
    - /v\d+\.\d+[a-z]/
addons:
  apt:
    sources:
    - travis-ci/sqlite3
    packages:
    - sqlite3
sudo: false
before_script:
    - npm install -g mocha
script:
- npm test
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: fCULY73WOwO0z3oQ3LvxPwB/nFyNbT8nFzPjfBRWILNnrfGjW+CNAnptmohL+QQ9GmZ9KQmjxScnR8wx/G4ifCgKFcIVNhZmRTtiansGTQI2XupEkTknpUqqGE+MgLG9AfYjDEznME7grzsJg0oUuDcXY9a4bAdHNKsd6uMLZMGzVY5rYpKiDjRenOnJ7Q7IQPFHUPaDJNfGMezXUZsyxcNautPDfctSW1LbdV7DG2DsuWODgA7bMFSkH6aA0fbsNE3S7BplMRMhs9xR2NDK31w5JYR39GKQuq6h0ueB/AquMs6oyktPf30uQGbn7n4ujXuuXwJneDNYNFIte9YF67NPK54rYdxQRykrf3XLwFkS//yqtlNUDfupNK51fD01KjDt0dtAH+0jrhzyOo4lMEpljWo9re/meIM5RV39lDphBIrrvEYHAe3wJuy80aWzpiI2skzFlGC3CAbHLRpvkr7QFcrB8qesu0HKkZTppMkfxDnzxKsHk6L8NDdYMntl5tQT0J1DExmO/t64emk19n1K3IFFwHiL3L6UYO7AXoLwEE2f7x1mt09tYzp5IOuUwrPkKFHR8m3eibrcTT01KhAqBFHvUmqkct+tmHM1M+N8RaDbFbjkqp6HNagACrp6noWoh7qz5pIX0SC5575Ro87ypO8kUxTL51D1eGdfCWM=
  app: ford-api-carlos-dias
  edge: true
  on: 
    tags: true
    all_branches: true
